<body>
<link href="<?php echo base_url();?>assets/css/dataTables.min.css" rel="stylesheet"/>
<!-- Tabel akun -->
	<div id="page-wrapper">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-12">
					<h1 class="page-header">Daftar Siswa</h1>
				</div>
			</div>
			<?php 
				$message=$this->session->flashdata('message');
				if (!empty($message)){
					echo $message;
				}
			?>
			<div class="row">
				<div class="col-md-12">
					<table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
						<thead>
							<tr>
								<th>NIS</th>
								<th>Nama</th>
								<th>Level</th>
								<th>Menu</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
							<tr>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
								<td>AAA</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
<!-- /.Tabel akun -->
<!-- jQuery -->


</body>